home/urls.py
from django.conf.urls import url
from django.urls import include, re_path

from django.contrib.auth import views as auth_views

from home import views
from . import views 
from home.views import ContactView, PrivacyView, TermsView,  AboutView, HomeView

app_name = 'home'


urlpatterns = [
    re_path(r'^$', HomeView.as_view(), name='home'),
    re_path(r'^privacy/', PrivacyView.as_view(), name='privacy' ),
    re_path(r'^terms/', TermsView.as_view(), name='terms'),
    re_path('contact/', ContactView.as_view(), name='Contact'),
    re_path(r'^about/', AboutView.as_view(), name='about'),

  
]



login/urls.py

from django.urls import include, path
from .views import login, client, shop
from django.conf import settings
from django.conf.urls import url
from django.urls import include, re_path
from django.urls import include ,path
from django.contrib.auth import (
    login,
    logout,
#     password_reset_confirm,
#      password_reset,
#     password_reset_done,
#     password_reset_complete
     )
from django.contrib.auth.views import(
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView
)
from django.contrib.auth.views import LogoutView
from django.contrib.auth import views as auth_views
from . import views as myapp_views
from . import views
from  .views import login 

app_name = 'login'

urlpatterns = [

    path('clients/', include(([
       

        #re_path(r'^delete/(?P<username>[\w|\W.-]+)/$', views.delete_user, name='delete-user')

    ]))),


    path('shops/', include(([
        #re_path(r'^profile/$',login.ProfileView.as_view(), name='profile'),
        

    ])))
 
]




    

website/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import include ,path ,re_path

from login.views import  client , shop, login


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls',namespace='home')),
    #path('outreach/',include('outreach.urls',namespace='outreach')),
    path('login/',include('login.urls',namespace='login')),
    path('', include('login.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', login.SignUpView.as_view(), name='signup'),
    path('accounts/signup/client/', client.ClientSignUpView.as_view(), name='client_signup'),
    path('accounts/signup/shop/', shop.ShopSignUpView.as_view(), name='shop_signup'),
   
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


home/forms.py
from django import forms
from home.models import Contact,Newsletter
from django.forms import ModelForm

from .models import *


class ContactForm(forms.ModelForm):
    phone  = forms.DecimalField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Write your phone number here...'
        }
    ))
    class Meta:
        model = Contact

        fields = [
            'name',
            'email',
            'content'
            
        ]


class NewsletterForm(forms.ModelForm):

    attrs={
        'class':'form-control',
        'placeholder': 'Write your email here...'
    }
    class Meta:
        model = Newsletter
        fields = [
            'email'
       ]

login/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.db import transaction
from django.forms.utils import ValidationError
from django.contrib.auth import get_user_model
from login.models import User, Client, Shop


class ClientSignUpForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta(UserCreationForm.Meta):
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2'
        )
        
        @transaction.atomic
        def save(self, commit=True):
            user = super(ClientSignUpForm, self).save(commit=False)
            User.username = self.cleaned_data['username']
            User.email = self.cleaned_data['email']
            user.is_client = True
            if commit:
                user.save()
            return user



class ShopSignUpForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta(UserCreationForm.Meta):
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2'
        )

        def save(self, commit=True):
            user = super(ShopSignUpForm, self).save(commit=True)
            User.username = self.cleaned_data['username']
            User.email = self.cleaned_data['email']
            user.is_shop = True
            if commit:
                user.save()
            return user



class EditProfileForm(UserChangeForm):

    class Meta:
        model = User
        fields = (
            'username',
            'email',
            'first_name',
            'last_name',
            'password'
        )


class EditShopForm(UserChangeForm):

    class Meta:
        #model = EditShopForm
        fields = (
            'shop_name',
            'description',
            'image',
            'city',
            'phone',
            'website'

        )

home/views.py


from django.views.generic import TemplateView
from django.shortcuts import render, redirect, HttpResponseRedirect, get_object_or_404
#from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from login.models import User
#from home.forms import HomeForm, HomeCreate
#from home.models import Post, Friend
#from .models import Create
from home.forms import ContactForm, NewsletterForm
from home.models import Contact, Privacy, Terms, Aboutpage
from login.models import Client, Shop

from django.utils.decorators import method_decorator
from django.views.generic import ListView, CreateView # new
from django.urls import reverse_lazy
from random import randint
from home.models import Post, Homepage, Aboutpage, Aboutpagee
from django.shortcuts import render, redirect, reverse
from django.conf import settings


import json


@login_required
def home(request):
    return render(request, 'core/home.html')


class HomeView(TemplateView):
    template_name = 'home/home.html'
    model = NewsletterForm
    form_class = NewsletterForm

    def get(self, request):
        form = NewsletterForm()
        posts = Post.objects.all()
        homepages = Homepage.objects.all()

        # Format content
        formatted_content = self.format_homepage_content(homepages.first().content)

        args = {
            'posts': posts, 'homepages': homepages, 'form': form, 'formatted_content': formatted_content
        }
        return render(request, self.template_name, args)

    def post(self, request):
        form = NewsletterForm(request.POST)
        if form.is_valid():
            newsletter = form.save(commit=False)
            newsletter.user = request.user
            newsletter.save()
            title = 'Thanks!!'
            confirm_message = "Thank you for subscribing to our newsletter. Email received."
            context = {'title': title, 'confirm_message': confirm_message }

            return render(request, self.template_name, context)

    def format_homepage_content(self, content):
        # Split the content into lines
        lines = content.split('\n')
        
        # Format the lines
        formatted_lines = []
        for line in lines:
            if line.strip():
                # Check if the line is a section title (ends with ':')
                if line.endswith(':'):
                    formatted_lines.append(f'<strong>{line}</strong>')
                else:
                    # Assume it's a list item without automatic numbering
                    formatted_lines.append(f'<div>{line.strip()}</div>')

        # Combine the lines into an HTML string
        formatted_content = "".join(formatted_lines)
        return formatted_content





class ContactView(CreateView):
    model = Contact
    form_class = ContactForm
    template_name = 'home/contact.html'
    success_url = reverse_lazy('shopp:product_list')

    def get(self, request):
        form = ContactForm()
        return render(request, self.template_name, {'form': form})

    def post(self,request):
        form = ContactForm(request.POST)
        if form.is_valid():
            contact = form.save(commit=False)
            contact.user = request.user
            contact.save()
            title = 'Thanks!!'
            confirm_message = 'Thanks for the message. We will get right back to you!'
            context = {'title': title, 'confirm_message': confirm_message}
        return render(request, self.template_name, context)
        #return redirect('shopp:product_list')



class PrivacyView(TemplateView):
    template_name = "home/privacy.html"

    def get(self, request):
        #form = PrivacyForm()
        privacy = Privacy.objects.all()#.order_by('-date')

        args = {'privacy': privacy }
        return render(request, self.template_name, args)

    def post(self, request):
        form = PrivacyForm()
        if form.is_valid():
            #privacy = form.save(commit=False)
            privacy = get_object_or_404(Privacy, id=id, slug=slug)
            privacy.user = request.user
            privacy.save()
            return redirect('home:privacy')
        args = {'privacy':privacy }
        return render(request, self.template_name, args)   


class TermsView(TemplateView):
    template_name = 'home/terms.html'

    def get(self, request):
        terms = Terms.objects.all()
        args = {'terms':terms }
        return render(request, self.template_name, args)

    def post(self, request):
        if form.is_valid():
            terms = get_object_or_404(Terms)
            terms.user = request.user
            terms.user()
            return redirect('home:terms')

        args = {'terms':terms}
        return render(request, self.template_name, args)

class AboutView(TemplateView):
    template_name = 'home/about.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        aboutpages = Aboutpagee.objects.all()
        context['aboutpages'] = aboutpages
        return context


login/views/client.py
from django.contrib import messages
from django.contrib.auth import login,logout
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.db.models import Count
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator



from login.decorators import client_required
from login.models import  Client, User
from django.views.generic import TemplateView , CreateView
from login.forms import  ClientSignUpForm



from django.core.mail import send_mail
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.template.loader import render_to_string
from django.core.mail import send_mail
from django.contrib.auth import login
from django.urls import reverse_lazy
from smtplib import SMTPAuthenticationError

class ClientSignUpView(CreateView):
    template_name = 'registration/signup_form.html'
    model = Client
    form_class = ClientSignUpForm

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'client'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)

        # Send thank you email to the user
        subject = 'Welcome to CramHub!'
        message = f"Hi {user.first_name},\n\n Discover a new era of Revision!"
        from_email = 'martin@gmail.com'  # Replace with your email
        recipient_list = [user.email]

        try:
            send_mail(subject, message, from_email, recipient_list)
        except SMTPAuthenticationError:
            pass  # Fail silently if email sending fails

        return redirect('bcom:home')


login/views/login.py
from django.shortcuts import redirect, render
from django.views.generic import TemplateView

from django.http import Http404
from django.contrib.auth import login, authenticate
from django.shortcuts import render, redirect, get_object_or_404
#from django.contrib.auth.forms import RegistrationForm
#from login.forms import ( EditProfileForm)
#from django.contrib.auth.models import User
from ..models import User
#from shopp.models import ResidentAddress
from django.contrib.auth.forms import UserChangeForm, PasswordChangeForm#, EditProfileForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from login.forms import  EditProfileForm#, contactForm
#from home.views import Post

from django.views.generic import TemplateView
from django.utils.decorators import method_decorator
#
from django.conf import settings
from django.core.mail import send_mail
from django.template.loader import get_template


from django.core.mail import send_mail
from django.shortcuts import redirect, render
from django.views.generic import TemplateView
from django.conf import settings

class SignUpView(TemplateView):
    template_name = 'registration/signup.html'

    def signup(self, request):
        if request.method == 'POST':
            # Process signup form data here
            
            # Send welcome email to the user
            user_email = request.POST['email']  # Assuming email is submitted in the signup form
            send_mail(
                'Welcome to My Website',  # Subject of the email
                'Thank you for signing up to My Website!',  # Message of the email
                settings.DEFAULT_FROM_EMAIL,  # From email address
                [user_email],  # To email address (recipient)
                fail_silently=False,  # Raise exceptions for errors
            )
            
            # Redirect to desired view after signup
            if request.user.is_authenticated:
                if request.user.is_shop:
                    return redirect('bcom:home')
                elif request.user.is_client:
                    return redirect('bcom:home')
                else:
                    return redirect('bcom:home')
            else:
                # Return an appropriate response for non-authenticated users
                return render(request, 'bcom:home')
        else:
            # Return an appropriate response for non-POST requests
            return render(request, self.template_name)


# class SignUpView(TemplateView):
#     template_name = 'registration/signup.html'

#     def home(self, request):
#         if request.user.is_authenticated:
#             if request.user.is_shop:
#                 return redirect('shopp:residentadressform')
#             else:

            
#                 return redirect('shopp:residentadressform')
#             if request.user.is_client:

#                 return redirect('shopp:residentadressform')
            
#             else:
#                 return redirect('shopp:residentadressform')
        
#         return render(request,'shopp:residentadressform')

#    def get(self, request):
#        if request.user.is_authenticated:
#            if request.user.is_client:
##                return redirect('shopp:product_list')
 #           else:
#                return redirect('shopp:product_list')
#        return render(request,'registration/signup.html')






@login_required
def login_admin(request):
    return render(request, 'admin/login.html')



login/views/shop.py

from django.contrib.auth import login
from django.contrib.auth.decorators import login_required

from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator


from login.decorators import client_required, shop_required
from login.models import Shop, User
from django.views.generic import TemplateView , CreateView
from login.forms import ShopSignUpForm


class ShopSignUpView(CreateView):
    template_name = 'registration/signup_form.html'
    model = Shop
    form_class = ShopSignUpForm

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'shop'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('shop:product_list')




login/templates/base.html
 {% load static %}
 <!DOCTYPE html>
 <html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    {% comment %} <meta name="viewport" content="width=device-width, initial-scale=1"> {% endcomment %}

    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap" rel="stylesheet">

    
   
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" 
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

     <!-- Add Bootstrap CSS -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3/dist/css/bootstrap.min.css">

<!-- Optional: Add Bootstrap Icons CSS -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.20.0/font/bootstrap-icons.css">

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.min.js" integrity="sha384-Rx+T1VzGupg4BHQYs2gCW9It+akI2MM/mndMCy36UVfodzcJcF0GGLxZIzObiEfa" crossorigin="anonymous"></script>
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
     integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">


     {% comment %} <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCjj5OT0bp2DdeZ0r59OBcduelJWX-SAA0&libraries=places&callback=initMap&solution_channel=GMP_QB_addressselection_v1_cABC" async defer></script> {% endcomment %}

    {% comment %} <meta name="viewport" content="width=device-width, initial-scale=1.0"> {% endcomment %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    {% load static %}
    <link rel="stylesheet" href="{% static 'login/style.css'%}" type="text/css">
    <link rel="shortcut icon" type="image/png" href="https://storage.googleapis.com/residentbucketheroku/datashop/2023/08/01/Green_Modern_Plants_Trifold_Brochure_1.png">

    <script src="https://cdnjs.cloudflare.com/ajax/libs/typed.js/2.0.12/typed.min.js"></script>




 
      {% block head %}
      <title>base</title>
    
      {% endblock %}
      
</head>
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-57L9LCVXMV"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-57L9LCVXMV');
</script>
<body>

  <nav class="navbar navbar-expand-lg navbar-light fixed-top" style="background-color: rgb(153, 5, 76); color: rgb(7, 104, 96); box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);">
    <a class="navbar-brand mx-auto" style="color: rgb(255, 255, 255)" href="{% url 'home:home'  %}">
        <h5><b>HealthBridge </b></h5>
    </a>
    <div class="collapse navbar-collapse justify-content-center" style="color: rgb(249, 249, 247)" id="navbarNav">
        <ul class="navbar-nav text-center">
            {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'home:home' %}" style="color: white;"><b>Home</b></a>
            </li>
            
            
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{ % url 'login:register'  %}" style="color: white;"><b>HealthBridge</b></a>
            </li>
            
            
            {% endif %}
        </ul>
    </div>
    <button class="navbar-toggler" type="button" data-toggle="modal" data-target="#mobileMenuModal">
        <span class="navbar-toggler-icon"></span>
    </button>
</nav>


<br>


<!-- Mobile Menu Modal -->
<div class="modal fade" id="mobileMenuModal" tabindex="-1" role="dialog" aria-labelledby="mobileMenuModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="mobileMenuModalLabel">Menu</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <ul class="navbar-nav">
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url  'home:home' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{ % url 'login:view_profile'  %}">Contact Us : </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{ % url 'home:memelords'  %}">Blog</a>
                    </li>
                    {% else %}
                    
                    <li class="nav-item">
                        <a class="nav-link" href="{ % url 'home:about'  %}">About</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
</div>
  
    {% block body%}
    <h1>Base</h1>
    {% endblock %}





    <!-- Optional JavaScript -->
   <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    
{% comment %} <script>
    "use strict";

    function initMap() {
      const CONFIGURATION = {
        "ctaTitle": "Checkout",
        "mapOptions": {"center":{"lat":37.4221,"lng":-122.0841},"fullscreenControl":true,"mapTypeControl":false,"streetViewControl":true,"zoom":11,"zoomControl":true,"maxZoom":22},
        "mapsApiKey": "AIzaSyCjj5OT0bp2DdeZ0r59OBcduelJWX-SAA0",
        "capabilities": {"addressAutocompleteControl":true,"mapDisplayControl":true,"ctaControl":true}
      };
      const componentForm = [
        'location',
        'locality',
        'administrative_area_level_1',
        'country',
        'postal_code',
      ];

      const getFormInputElement = (component) => document.getElementById(component + '-input');
      const map = new google.maps.Map(document.getElementById("gmp-map"), {
        zoom: CONFIGURATION.mapOptions.zoom,
        center: { lat: 37.4221, lng: -122.0841 },
        mapTypeControl: false,
        fullscreenControl: CONFIGURATION.mapOptions.fullscreenControl,
        zoomControl: CONFIGURATION.mapOptions.zoomControl,
        streetViewControl: CONFIGURATION.mapOptions.streetViewControl
      });
      const marker = new google.maps.Marker({map: map, draggable: false});
      const autocompleteInput = getFormInputElement('location');
      const autocomplete = new google.maps.places.Autocomplete(autocompleteInput, {
        fields: ["address_components", "geometry", "name"],
        types: ["address"],
      });
      autocomplete.addListener('place_changed', function () {
        marker.setVisible(false);
        const place = autocomplete.getPlace();
        if (!place.geometry) {
          // User entered the name of a Place that was not suggested and
          // pressed the Enter key, or the Place Details request failed.
          window.alert('No details available for input: \'' + place.name + '\'');
          return;
        }
        renderAddress(place);
        fillInAddress(place);
      });

      function fillInAddress(place) {  // optional parameter
        const addressNameFormat = {
          'street_number': 'short_name',
          'route': 'long_name',
          'locality': 'long_name',
          'administrative_area_level_1': 'short_name',
          'country': 'long_name',
          'postal_code': 'short_name',
        };
        const getAddressComp = function (type) {
          for (const component of place.address_components) {
            if (component.types[0] === type) {
              return component[addressNameFormat[type]];
            }
          }
          return '';
        };
        getFormInputElement('location').value = getAddressComp('street_number') + ' '
                  + getAddressComp('route');
        for (const component of componentForm) {
          // Location field is handled separately above as it has different logic.
          if (component !== 'location') {
            getFormInputElement(component).value = getAddressComp(component);
          }
        }
      }

      function renderAddress(place) {
        map.setCenter(place.geometry.location);
        marker.setPosition(place.geometry.location);
        marker.setVisible(true);
      }
    }
    </script> 
    
    {% endcomment %}


    <script>
      // Wait for the DOM to be ready
      document.addEventListener("DOMContentLoaded", function () {
        // Define the text to be typed
        const featuredText = "Featured";
    
        // Function to start the typing animation loop
        function startTyping() {
          const typed = new Typed("#typing-text", {
            strings: [featuredText],
            typeSpeed: 800, // Speed of typing in milliseconds
            backSpeed: 100, // Speed of backspacing in milliseconds (lower value for slower backspace)
            startDelay: 20000, // Delay before typing starts in milliseconds
            loop: false, // Disable looping for this instance
            showCursor: true, // Show the cursor
            cursorChar: "_", // Customize the cursor character
            onComplete: function () {
              // After typing is complete, add a delay before starting the next loop
              setTimeout(startTyping, 30000); // 300000 milliseconds (5 minutes) delay before next loop
            },
          });
        }
    
        // Start the typing animation loop
        startTyping();
      });
    </script>
    
    
    
    

    

</body>
<footer class="bg-custom text-light py-4">
  <style>
    /* Define the custom color in CSS */
    .bg-custom {
        background-color: #b1034c;
    }
</style>
  <div class="container">
      <div class="row">
          <div class="col-md-4">
              <h5>Contact Us</h5>
              <p>HealthBridge Hospital</p>
              <p>Nakuru - Nakuru Highway</p>
              <p>Nakuru, Kenya</p>
              <p>Email: HealthBridge@gmail.com</p>
              <p>Phone: +254 703 752 215 0r +254 708 374 241</p>
          </div>
          <div class="col-md-4">
              <h5>Quick Links</h5>
              <ul class="list-unstyled">
                <li><a href="#" class="text-white fw-bold">Home</a></li>
                <li><a href="#" class="text-white fw-bold">About Us</a></li>
                <li><a href="#" class="text-white fw-bold">Services</a></li>
                <li><a href="#" class="text-white fw-bold">Doctors</a></li>
                <li><a href="#" class="text-white fw-bold">Contact</a></li>
            </ul>
            
          </div>
          <div class="col-md-4">
              <h5>Follow Us</h5>
              <ul class="list-unstyled">
                  <li><a href="#" class="text-white fw-bold">Facebook</a></li>
                  <li><a href="#" class="text-white fw-bold">Twitter</a></li>
                  <li><a href="#" class="text-white fw-bold">Instagram</a></li>
              </ul>
          </div>
      </div>
      <hr>
      <div class="row">
          <div class="col-md-12 text-center">
              <p>&copy; 2024 HealthBridge Hospital. All rights reserved.</p> <p>Built by Joytech HEALTHCARE 2024 Email : machuamartin@gmail.com</p>
          </div>
      </div>
  </div>
</footer>
</html>

login/templates/home.html
{% extends 'base.html' %}

{% block body %}
  <h2>Welcome to CramHub  <span class="icon-emo-happy"></span></h2>
  <p class="lead">
    If you already have an account, go ahead and <a href="{% url 'login' %}">log in</a>. If you are new , get started
    by creating a <a href="{% url 'client_signup' %}">Signup</a> 
  </p>
  <hr>
  
{% endblock body %}